<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYcWo7Tm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYcWo7Tm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYcWo7Tm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYcWo7Tm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYcWo7Tm\App_KernelDevDebugContainer([
    'container.build_hash' => 'YcWo7Tm',
    'container.build_id' => 'c9c5a07d',
    'container.build_time' => 1734289547,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYcWo7Tm');
